name = "accounts-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "accounts-db"
database_id = "5c531d6a-3897-487d-bfe6-e8f582152a71"
